# HW0

## Problem 1: Comma Separated Factorials

In [1]:
def fact(x):
    result = 1
    while(x>1):
        result *= x
        x = x-1
    return result

def main(x):
    if(x==1):
        return "1"
    result = ""
    for i in range(x):
        if(i==0):
            result = str(fact(i+1))
        else:
            result = str(fact(i+1)) + "," + result
    return result

print(main(9))

362880,40320,5040,720,120,24,6,2,1


## Problem 2: List Manipulation

In [2]:
def list_func(list1, list2):
    list2.sort(reverse=True)
    list2.pop()
    return list2

In [3]:
def list_func(list1, list2):
    list1.reverse()
    return list1

In [4]:
def list_func(list1, list2):
    set1 = set(list1)
    set2 = set(list2)
    combined_set = set1 | set2
    combined_list = list(combined_set)
    combined_list.sort()
    return combined_list

In [5]:
def list_func(list1, list2):
    list2d = []
    list2d.append(list1)
    list2d.append(list2)
    return list2d

In [6]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9]
print(list_func(list1, list2))

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]


## Problem 3: Set Manipulation

In [7]:
def set_func(set1, set2, set3):
    return set1 | set2 | set3

In [8]:
def set_func(set1, set2, set3):
    return set1 & set2 & set3

In [9]:
def set_func(set1, set2, set3):
    # inter3 = set1 & set2 & set3
    inter12 = set1 & set2
    inter13 = set1 & set3
    inter23 = set2 & set3
    result = (set1 | set2 | set3) - inter12 - inter23 - inter13
    return result

In [10]:
set1 = {1,2,3}
set2 = {2,3,4}
set3 = {3,4,5}
print(set_func(set1, set2, set3))

{1, 5}


below are just numpy testing code

In [11]:
import numpy as np

In [12]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(np.concatenate((a,c), axis=0))
print(np.concatenate((a,c), axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12]]


In [13]:
a = np.array([1, 2, 3, 4, 5, 6])
a2 = a[np.newaxis, :]
a3 = a.reshape(1,6)
b = np.expand_dims(a, axis=1)
b2 = a.reshape(6,1)
print(a2)
print(a3)
print(b)
print(b2)

[[1 2 3 4 5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [14]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([1, 2, 3, 4, 5, 6])
c = np.array([1, 3, 4, 5, 6])
print(a+b)
rng = np.random.default_rng()
rng.integers(5, size=(2,4)) # generate random integers in range [0,5) into a nparray of shape (2,4)

[ 2  4  6  8 10 12]


array([[0, 2, 4, 0],
       [2, 2, 4, 2]])

## Problem 4: Under Attack

In [15]:
def createMatrix():
    matrix = np.array([[1,1,1,1,1],[1,0,0,0,1],[1,0,2,0,1],[1,0,0,0,1],[1,1,1,1,1]])
    return matrix

In [16]:
def createMatrix2():
    matrix = np.array([[1,1,1,1,1],[1,2,0,0,1],[1,0,0,0,1],[1,0,0,0,1],[1,1,1,1,1]])
    return matrix

In [17]:
def get_pawn_index(board):
    return np.where(board == 2)

In [18]:
def check_knight(board, pawn, x, y):
    newx = pawn[0][0]+x
    newy = pawn[1][0]+y
    # print(x,y,newx,newy)
    if(newx<0 or newx>5 or newy<0 or newy>5):
        pass
    elif (board[newx][newy] == 1):
        print("(%d,%d)"%(newx, newy))

In [19]:
def detect(board):
    pawn = get_pawn_index(board)
    check_knight(board, pawn, 2, 1)
    check_knight(board, pawn, 2, -1)
    check_knight(board, pawn, -2, 1)
    check_knight(board, pawn, -2, -1)
    check_knight(board, pawn, 1, 2)
    check_knight(board, pawn, 1, -2)
    check_knight(board, pawn, -1, 2)
    check_knight(board, pawn, -1, -2)

In [20]:
print(createMatrix())
detect(createMatrix())

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 2 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
(4,3)
(4,1)
(0,3)
(0,1)
(3,4)
(3,0)
(1,4)
(1,0)


In [21]:
print(createMatrix2())
detect(createMatrix2())

[[1 1 1 1 1]
 [1 2 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
(3,0)
(0,3)


## Problem 5: Graphs

In [22]:
def create_graph():
    graph = {
        "A": ["D", "E"],
        "B": ["E", "F"],
        "C": ["E"],
        "D": ["A", "E"],
        "E": ["A", "B", "C", "D"],
        "F": ["B"],
        "G": []
    }
    return graph

In [23]:
def isolated_node(graph):
    result = 0
    for k in graph.keys():
        if graph[k]:
            pass
        else:
            result += 1
    return result

In [24]:
def non_isolated_node(graph):
    result = 0
    for k in graph.keys():
        if graph[k]:
            result += 1
        else:
            pass
    return result

In [25]:
def find_unique_edge(graph):
    for k in graph.keys():
        for des in graph[k]:
            if des < k:
                pass
            else:
                print("(%s,%s)"%(k, des))

In [26]:
def construct_matrix(graph):
    # print(ord("a"))
    # print(chr(97))
    result = np.zeros((len(graph), len(graph)))
    for k in graph.keys():
        for des in graph[k]:
            result[ord(k)-ord("A")][ord(des)-ord("A")]=1
    return result

In [27]:
print(isolated_node(create_graph()))
print(non_isolated_node(create_graph()))
find_unique_edge(create_graph())
construct_matrix(create_graph())

1
6
(A,D)
(A,E)
(B,E)
(B,F)
(C,E)
(D,E)


array([[0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

## Problem 6: Supermarket

In [28]:
import heapq

In [47]:
class PriorityQueue():
    def __init__(self):
        self.data = []
        heapq.heapify(self.data)
    
    def push(self, item, price):
        heapq.heappush(self.data, (price, item))

    # def printpq(self):
    #     for item in self.data:
    #         print(item)

    def isempty(self):
        return len(self.data) == 0
    
    def pop(self):
        return heapq.heappop(self.data)[1].replace("'","")

In [48]:
pq = PriorityQueue()
pq.push("orange",3.7)
pq.push("carrot",5.1)
pq.push("kiwi",2.4)
pq.push("apple",3.7)
while not pq.isempty():
    print(pq.pop())

kiwi
apple
orange
carrot
